/**
 * KraftedFormat — Standalone Browser Bundle
 * Complete save/load engine for .krafted files.
 * Dependency: JSZip (loaded above)
 */
(function (global) {
  'use strict';
  var JSZip = global.JSZip;
  if (!JSZip) { console.error('[KraftedFormat] JSZip is required.'); return; }
  var SCHEMA_VERSION = 1;
  var DEFAULT_CANVAS = { width: 1920, height: 1080, backgroundColor: '#1a1a1a' };
  var DEFAULT_VIEWPORT = { zoom: 1.0, panX: 0, panY: 0 };
  var NODE_TYPE = { IMAGE: 'image', VIDEO: 'video', AUDIO: 'audio', TEXT: 'text', DRAW: 'draw', GROUP: 'group', LINK: 'link', TODO: 'todo', MINDMAP: 'mindmap' };
  function buildTransform(x,y,sx,sy,r){return {x:x||0,y:y||0,scaleX:sx||1,scaleY:sy||1,rotation:r||0};}
  function buildCrop(x,y,w,h,p){return {x:x||0,y:y||0,w:w||0,h:h||0,points:p||null};}
  function buildAssetRef(id,fn,mt,sz,nw,nh){return {id:id,filename:fn||'',mimeType:mt||'application/octet-stream',size:sz||0,natW:nw||0,natH:nh||0};}
  function buildPlayback(st,et,lp,mu,pr){return {startTime:st||0,endTime:et||0,loop:lp||false,muted:mu!==undefined?mu:true,playbackRate:pr||1};}
  function buildAdjustments(br,co,sa,hr,bl,se,gr,te,vi,sh,hi,gn){return {brightness:br!==undefined?br:100,contrast:co!==undefined?co:100,saturate:sa!==undefined?sa:100,hueRotate:hr||0,blur:bl||0,sepia:se||0,grayscale:gr||0,temp:te||0,vignette:vi||0,shadow:sh||0,highlight:hi||0,grain:gn||0};}
  function buildMask(id,nm,en,ty,co,to,fe){return {id:id,name:nm||'',enabled:en!==undefined?en:true,type:ty||'color',color:co||'#ffffff',tolerance:to||30,feather:fe||0};}
  function buildTextNode(id,tx,ff,fs,fw,cl,tr,zi){return {id:id,type:NODE_TYPE.TEXT,text:tx||'',fontFamily:ff||'Inter',fontSize:fs||16,fontWeight:fw||'400',color:cl||'#ffffff',textAlign:'left',transform:tr||buildTransform(),zIndex:zi||0,opacity:1,visible:true,locked:false};}
  function buildImageNode(id,ai,tr,cr,ad,zi){return {id:id,type:NODE_TYPE.IMAGE,assetId:ai,transform:tr||buildTransform(),crop:cr||null,adjustments:ad||buildAdjustments(),zIndex:zi||0,opacity:1,visible:true,locked:false,flipH:false,flipV:false};}
  function buildVideoNode(id,ai,tr,cr,ad,pb,zi){return {id:id,type:NODE_TYPE.VIDEO,assetId:ai,transform:tr||buildTransform(),crop:cr||null,adjustments:ad||buildAdjustments(),playback:pb||buildPlayback(),zIndex:zi||0,opacity:1,visible:true,locked:false,flipH:false,flipV:false,fps:null,fpsManual:false};}
  function buildAudioNode(id,ai,tr,zi){return {id:id,type:NODE_TYPE.AUDIO,assetId:ai,transform:tr||buildTransform(),zIndex:zi||0,opacity:1,visible:true,locked:false};}
  function buildDrawNode(id,si,mo,co,sz,op,tr,zi){return {id:id,type:NODE_TYPE.DRAW,strokeId:si,drawMode:mo||'pen',drawColor:co||'#ffffff',drawSize:sz||2,drawOpacity:op!==undefined?op:1,transform:tr||buildTransform(),zIndex:zi||0,locked:false};}
  function buildLinkNode(id,ur,ti,de,tr,zi){return {id:id,type:NODE_TYPE.LINK,linkUrl:ur||'',linkTitle:ti||'',linkDesc:de||'',transform:tr||buildTransform(),zIndex:zi||0,opacity:1,visible:true,locked:false};}
  function buildGroup(id,co,mi){return {id:id,type:NODE_TYPE.GROUP,color:co||'#7856ff',memberIds:mi||[]};}
  function createEmptyManifest(){return {_schema:SCHEMA_VERSION,_app:'Krafted',_createdAt:new Date().toISOString(),_modifiedAt:new Date().toISOString(),canvas:{width:DEFAULT_CANVAS.width,height:DEFAULT_CANVAS.height,backgroundColor:DEFAULT_CANVAS.backgroundColor},viewport:{zoom:DEFAULT_VIEWPORT.zoom,panX:DEFAULT_VIEWPORT.panX,panY:DEFAULT_VIEWPORT.panY},nodes:[],texts:[],groups:[],drawStrokes:[],assets:{},counter:{nextId:1,nextZ:1,nextStrokeId:1,nextGroupId:1}};}
  function validateManifest(m){var e=[];if(!m){e.push('manifest is null');return {valid:false,errors:e};}if(!m._schema)e.push('missing _schema');else if(typeof m._schema!=='number')e.push('_schema must be number');if(!m.canvas)e.push('missing canvas');else {if(typeof m.canvas.width!=='number')e.push('canvas.width must be number');if(typeof m.canvas.height!=='number')e.push('canvas.height must be number');}if(!Array.isArray(m.nodes))e.push('nodes must be array');if(m._schema>SCHEMA_VERSION)e.push('schema too new');return {valid:e.length===0,errors:e};}
  var Schema = {VERSION:SCHEMA_VERSION,NODE_TYPE:NODE_TYPE,DEFAULT_CANVAS:DEFAULT_CANVAS,DEFAULT_VIEWPORT:DEFAULT_VIEWPORT,buildTransform:buildTransform,buildCrop:buildCrop,buildAssetRef:buildAssetRef,buildPlayback:buildPlayback,buildAdjustments:buildAdjustments,buildMask:buildMask,buildTextNode:buildTextNode,buildImageNode:buildImageNode,buildVideoNode:buildVideoNode,buildAudioNode:buildAudioNode,buildDrawNode:buildDrawNode,buildLinkNode:buildLinkNode,buildGroup:buildGroup,createEmptyManifest:createEmptyManifest,validateManifest:validateManifest};
  function mimeToExt(m,fb){if(!m)return fb||'bin';var x=m.toLowerCase();if(x.includes('video/mp4'))return 'mp4';if(x.includes('video/webm'))return 'webm';if(x.includes('video/ogg'))return 'ogv';if(x.includes('video/quicktime'))return 'mov';if(x.includes('video/'))return 'mp4';if(x.includes('image/png'))return 'png';if(x.includes('image/gif'))return 'gif';if(x.includes('image/webp'))return 'webp';if(x.includes('image/jpeg'))return 'jpg';if(x.includes('image/svg'))return 'svg';if(x.includes('image/'))return 'png';if(x.includes('audio/wav'))return 'wav';if(x.includes('audio/mpeg'))return 'mp3';if(x.includes('audio/ogg'))return 'ogg';if(x.includes('audio/'))return 'mp3';return fb||'bin';}
  function formatBytes(b){if(b<1024)return b+' B';if(b<1024*1024)return (b/1024).toFixed(1)+' KB';if(b<1024*1024*1024)return (b/1024/1024).toFixed(1)+' MB';return (b/1024/1024/1024).toFixed(2)+' GB';}
  function countMediaNodes(m){var v=0,i=0,a=0;var ns=m.nodes||[];for(var j=0;j<ns.length;j++){var n=ns[j];if(!n.assetId)continue;if(n.type==='video')v++;else if(n.type==='audio')a++;else i++;}return {video:v,image:i,audio:a,total:v+i+a};}
  async function buildKpak(manifest,options){var opts=options||{};var mf=opts.mediaFetcher||null;var onP=opts.onProgress||null;var comp=opts.compression||'STORE';var v=Schema.validateManifest(manifest);if(!v.valid)throw new Error('Invalid manifest: '+v.errors.join('; '));function rp(msg){if(onP)onP({phase:'pack',message:msg});}var zip=new JSZip();rp('Writing manifest...');manifest._modifiedAt=new Date().toISOString();zip.file('manifest.json',JSON.stringify(manifest,null,2));var mns=(manifest.nodes||[]).filter(function(n){return n.assetId&&['image','video','audio'].indexOf(n.type)!==-1;});if(mns.length===0||!mf){rp('No media to pack');var zb1=await zip.generateAsync({type:'blob',compression:comp});return {zipBlob:zb1,packed:0,skipped:0,totalSize:zb1.size};}rp('Packing '+mns.length+' media...');var pk=0,sk=0,ts=0;for(var i=0;i<mns.length;i++){var node=mns[i];var lb=node.type.charAt(0).toUpperCase()+node.type.slice(1);var msg='Packing '+lb+' '+(i+1)+'/'+mns.length+'...';if(onP)onP({phase:'pack',current:i+1,total:mns.length,message:msg});else rp(msg);try{var blob=await mf(node);if(!blob||blob.size===0){sk++;continue;}var ext=mimeToExt(blob.type,node.type==='video'?'mp4':'png');zip.file('media/'+node.id+'.'+ext,blob,{binary:true,compression:'STORE'});pk++;ts+=blob.size;if(i%3===0)await new Promise(function(r){setTimeout(r,0);});}catch(e){sk++;}}rp('Generating zip...');var zb=await zip.generateAsync({type:'blob',compression:comp},function(meta){if(onP&&meta.percent)onP({phase:'zip',percent:meta.percent,message:'Zipping '+meta.percent.toFixed(0)+'%'});});rp('Done — '+formatBytes(zb.size)+', '+pk+' media, '+(sk>0?sk+' skipped':'0 skipped'));return {zipBlob:zb,packed:pk,skipped:sk,totalSize:ts};}
  async function encryptWithLock(zb,pw){if(typeof crypto==='undefined'||!crypto.subtle)throw new Error('Web Crypto API required');var sb=new Uint8Array(16);crypto.getRandomValues(sb);var salt=Array.from(sb).map(function(b){return b.toString(16).padStart(2,'0');}).join('');var enc=new TextEncoder();var km=await crypto.subtle.importKey('raw',enc.encode(pw),'PBKDF2',false,['deriveBits']);var hb=await crypto.subtle.deriveBits({name:'PBKDF2',salt:enc.encode(salt),iterations:100000,hash:'SHA-256'},km,256);var hash=Array.from(new Uint8Array(hb)).map(function(b){return b.toString(16).padStart(2,'0');}).join('');var b64=await new Promise(function(rs,rj){var r=new FileReader();r.onload=function(){rs(r.result);};r.onerror=function(){rj(r.error);};r.readAsDataURL(zb);});var lw={_kraftedLock:{v:1,hash:hash,salt:salt},_kpakData:b64};return new Blob([JSON.stringify(lw)],{type:'application/locked-kpak'});}
  function generatePassword(len){var ch='ABCDEFGHJKLMNPQRSTUVWXYZabcdefghjkmnpqrstuvwxyz23456789';var by=new Uint8Array(len);crypto.getRandomValues(by);var pw='';for(var i=0;i<len;i++)pw+=ch[by[i]%ch.length];return pw;}
  function downloadBlob(blob,name){return new Promise(function(rs,rj){try{var u=URL.createObjectURL(blob);var l=document.createElement('a');l.download=name;l.href=u;document.body.appendChild(l);l.click();document.body.removeChild(l);setTimeout(function(){URL.revokeObjectURL(u);},5000);rs(true);}catch(e){rj(e);}});}
  async function writeToHandle(h,blob){var w=await h.createWritable();await w.write(blob);await w.close();}
  async function requestSaveHandle(name){if(!window.showSaveFilePicker)return {handle:null,name:null};try{var h=await window.showSaveFilePicker({suggestedName:name,types:[{description:'Krafted Package',accept:{'application/zip':['.kpak']}}]});return {handle:h,name:h.name};}catch(e){if(e.name==='AbortError')return {handle:null,name:null,cancelled:true};return {handle:null,name:null};}}
  var Writer = {mimeToExt:mimeToExt,formatBytes:formatBytes,countMediaNodes:countMediaNodes,buildKpak:buildKpak,encryptWithLock:encryptWithLock,generatePassword:generatePassword,downloadBlob:downloadBlob,writeToHandle:writeToHandle,requestSaveHandle:requestSaveHandle};
  function detectFormat(file){var n=(file.name||'').toLowerCase();if(n.endsWith('.kpak')||n.endsWith('.zip'))return 'kpak';if(n.endsWith('.json')||n.endsWith('.krafted'))return 'json';if(file.type==='application/zip'||file.type==='application/x-zip-compressed')return 'kpak';if(file.type==='application/json')return 'json';return 'unknown';}
  function readAsText(file){return new Promise(function(rs,rj){var r=new FileReader();r.onload=function(){rs(r.result);};r.onerror=function(){rj(r.error);};r.readAsText(file);});}
  function readFirstByte(file){return file.slice(0,1).text();}
  function base64ToBytes(b64){var raw=atob(b64.split(',')[1]||b64);var bytes=new Uint8Array(raw.length);for(var i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);return bytes;}
  async function remapMediaFromZip(manifest,zip){var me=Object.keys(zip.files).filter(function(p){return p.startsWith('media/')&&!p.endsWith('/');});var rc=0;var items=manifest.nodes||manifest.items||[];if(manifest.items&&!manifest.nodes)manifest.nodes=manifest.items;for(var i=0;i<items.length;i++){var node=items[i];var nt=node.type||(node.isAudio?'audio':node.isVideo?'video':node.isGif?'image':node.assetId?'image':null);if(!node.assetId||['image','video','audio'].indexOf(nt)===-1)continue;var pf='media/'+node.id+'.';var ep=null;for(var j=0;j<me.length;j++){if(me[j].startsWith(pf)){ep=me[j];break;}}if(!ep)continue;try{var blob=await zip.file(ep).async('blob');if(blob&&blob.size>0){node._blobUrl=URL.createObjectURL(blob);node._blobSize=blob.size;node._blobType=blob.type;if(!node.src)node.src=node._blobUrl;rc++;}}catch(e){}}return {manifest:manifest,restoredCount:rc};}
  async function verifyLockPassword(lock,pw,mp){if(mp&&pw===mp)return true;if(typeof crypto==='undefined'||!crypto.subtle)throw new Error('Web Crypto API required');var enc=new TextEncoder();var km=await crypto.subtle.importKey('raw',enc.encode(pw),'PBKDF2',false,['deriveBits']);var hb=await crypto.subtle.deriveBits({name:'PBKDF2',salt:enc.encode(lock.salt),iterations:100000,hash:'SHA-256'},km,256);var hash=Array.from(new Uint8Array(hb)).map(function(b){return b.toString(16).padStart(2,'0');}).join('');return hash===lock.hash;}
  async function loadLockedKpak(file,options){var opts=options||{};var pp=opts.passwordProvider;var mp=opts.masterPassword||null;var onP=opts.onProgress||null;function rp(msg){if(onP)onP({phase:'load',message:msg});}rp('Reading locked package...');var text=await readAsText(file);var wrapper;try{wrapper=JSON.parse(text);}catch(e){throw new Error('Invalid locked kpak: not valid JSON');}if(!wrapper._kraftedLock||!wrapper._kpakData)throw new Error('Invalid locked kpak');var lock=wrapper._kraftedLock;if(!pp)throw new Error('Password required');var unlocked=false;while(!unlocked){var pw=await pp();if(pw===false||pw===null)throw new Error('Load cancelled by user');unlocked=await verifyLockPassword(lock,pw,mp);if(!unlocked)console.warn('[KraftedFormat] Wrong password');}rp('Password accepted, unpacking...');var bytes=base64ToBytes(wrapper._kpakData);return loadKpakBlob(new Blob([bytes],{type:'application/zip'}),options);}
  async function loadKpakBlob(zb,options){var opts=options||{};var onP=opts.onProgress||null;function rp(msg){if(onP)onP({phase:'load',message:msg});}rp('Loading zip...');var zip=await JSZip.loadAsync(zb);var mf=zip.file('manifest.json');if(!mf)throw new Error('Invalid .kpak: no manifest.json');rp('Parsing manifest...');var mj=await mf.async('string');var manifest=JSON.parse(mj);if(manifest._kraftedLock){var lock=manifest._kraftedLock;if(opts.passwordProvider){var unlocked=false;while(!unlocked){var pw=await opts.passwordProvider();if(pw===false)throw new Error('Load cancelled');unlocked=await verifyLockPassword(lock,pw,opts.masterPassword);}delete manifest._kraftedLock;}}rp('Restoring media...');var result=await remapMediaFromZip(manifest,zip);rp('Loaded — '+(manifest.nodes||[]).length+' nodes, '+result.restoredCount+' media');return {manifest:manifest,restoredCount:result.restoredCount,format:'kpak'};}
  async function loadPlainJson(file,options){var opts=options||{};var onP=opts.onProgress||null;function rp(msg){if(onP)onP({phase:'load',message:msg});}var text=await readAsText(file);var manifest;try{manifest=JSON.parse(text);}catch(e){throw new Error('Invalid JSON: '+e.message);}if(manifest._kraftedLock&&manifest._kpakData){rp('Detected locked kpak...');return loadLockedKpak(file,options);}if(manifest._kraftedLock&&!manifest._kpakData){if(opts.passwordProvider){var lock=manifest._kraftedLock;var unlocked=false;while(!unlocked){var pw=await opts.passwordProvider();if(pw===false)throw new Error('Load cancelled');unlocked=await verifyLockPassword(lock,pw,opts.masterPassword);}delete manifest._kraftedLock;}}rp('Loaded — plain JSON, '+(manifest.nodes||manifest.items||[]).length+' items');if(manifest.items&&!manifest.nodes)manifest.nodes=manifest.items;return {manifest:manifest,restoredCount:0,format:'json'};}
  async function loadFile(file,options){if(!file)throw new Error('No file');var fmt=detectFormat(file);function rp(msg){if(options&&options.onProgress)options.onProgress({phase:'load',message:msg});}rp('Loading '+fmt+' file ('+Writer.formatBytes(file.size)+')...');var result;if(fmt==='kpak'){var fb=await readFirstByte(file);if(fb==='{'){rp('Detected locked kpak');result=await loadLockedKpak(file,options);}else result=await loadKpakBlob(file,options);}else if(fmt==='json'){result=await loadPlainJson(file,options);}else{try{rp('Unknown format, trying zip...');result=await loadKpakBlob(file,options);}catch(e){rp('Zip failed, trying JSON...');result=await loadPlainJson(file,options);}}result.fileSize=file.size;result.fileName=file.name;return result;}
  function buildBlobUrlMap(manifest){var map=new Map();var nodes=manifest.nodes||[];for(var i=0;i<nodes.length;i++){if(nodes[i]._blobUrl)map.set(nodes[i].id,nodes[i]._blobUrl);}return map;}
  var Reader = {detectFormat:detectFormat,readAsText:readAsText,readFirstByte:readFirstByte,base64ToBytes:base64ToBytes,remapMediaFromZip:remapMediaFromZip,verifyLockPassword:verifyLockPassword,loadLockedKpak:loadLockedKpak,loadKpakBlob:loadKpakBlob,loadPlainJson:loadPlainJson,loadFile:loadFile,buildBlobUrlMap:buildBlobUrlMap};
  function KraftedFile(){this.manifest=Schema.createEmptyManifest();this._blobUrlCache=new Map();this._loadedFrom=null;}
  KraftedFile.prototype={get nodes(){return this.manifest.nodes;},get texts(){return this.manifest.texts;},get groups(){return this.manifest.groups;},get canvas(){return this.manifest.canvas;},get viewport(){return this.manifest.viewport;},get assets(){return this.manifest.assets;},get counter(){return this.manifest.counter;},get schemaVersion(){return this.manifest._schema;},get createdAt(){return this.manifest._createdAt;},get modifiedAt(){return this.manifest._modifiedAt;},get loadedFrom(){return this._loadedFrom;},addNode:function(node){if(!node.id)node.id='node_'+(this.counter.nextId++);if(!node.zIndex&&node.zIndex!==0)node.zIndex=this.counter.nextZ++;this.nodes.push(node);},findNode:function(id){for(var i=0;i<this.nodes.length;i++){if(this.nodes[i].id===id)return this.nodes[i];}return null;},removeNode:function(id){for(var i=0;i<this.nodes.length;i++){if(this.nodes[i].id===id){this.nodes.splice(i,1);return;}}},addText:function(t){if(!t.id)t.id='text_'+(this.counter.nextId++);this.texts.push(t);},addGroup:function(g){if(!g.id)g.id='group_'+(this.counter.nextGroupId++);this.groups.push(g);},getBlobUrl:function(id){return this._blobUrlCache.get(id)||null;},setBlobUrl:function(id,url){this._blobUrlCache.set(id,url);},releaseBlobUrls:function(){var urls=this._blobUrlCache.values();var e=urls.next();while(!e.done){try{URL.revokeObjectURL(e.value);}catch(ex){}e=urls.next();}this._blobUrlCache.clear();},save:async function(options){var opts=options||{};var result=await Writer.buildKpak(this.manifest,{mediaFetcher:opts.mediaFetcher,compression:opts.compression,onProgress:opts.onProgress});var zb=result.zipBlob;if(opts.lock&&opts.lock.password){if(opts.onProgress)opts.onProgress({phase:'lock',message:'Encrypting...'});zb=await Writer.encryptWithLock(zb,opts.lock.password);}return {zipBlob:zb,packed:result.packed,skipped:result.skipped};},saveToHandle:async function(h,options){var r=await this.save(options);await Writer.writeToHandle(h,r.zipBlob);return r;},saveAndDownload:async function(options,name){var n=name||'krafted_'+new Date().toISOString().slice(0,10)+'.kpak';var r=await this.save(options);await Writer.downloadBlob(r.zipBlob,n);return r;},load:async function(file,options){this.releaseBlobUrls();var result=await Reader.loadFile(file,options);this.manifest=result.manifest;this._loadedFrom={format:result.format,fileName:result.fileName,fileSize:result.fileSize};var nodes=this.manifest.nodes||[];for(var i=0;i<nodes.length;i++){if(nodes[i]._blobUrl)this._blobUrlCache.set(nodes[i].id,nodes[i]._blobUrl);}return this;},toJSON:function(){return JSON.parse(JSON.stringify(this.manifest));},toString:function(){return JSON.stringify(this.manifest,null,2);},snapshot:function(){return KraftedFile.fromManifest(JSON.parse(JSON.stringify(this.manifest)));}};
  KraftedFile.fromManifest=function(m){var b=new KraftedFile();b.manifest=m;return b;};
  global.KraftedFormat = {Schema:Schema,Writer:Writer,Reader:Reader,KraftedFile:KraftedFile};
  console.log('[KraftedFormat] Engine loaded — Schema v'+Schema.VERSION+', Writer + Reader + KraftedFile ready.');
})(typeof window !== 'undefined' ? window : this);